version: '3.8'

# Docker Stack para Swarm 3-node (fog-manager, fog-worker-01, fog-worker-02)
# Traefik rodará no manager, Web pode rodar em qualquer node (load balanced)

services:
  traefik:
    image: traefik:v2.10
    command:
      - --log.level=INFO
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - fog-network
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  web:
    image: evertonsantos2025/morea-ds-web:latest
    env_file:
      - .env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - morea-media:/app/media
      - morea-static:/app/static
    networks:
      - fog-network
      - morea-network
    deploy:
      replicas: 2  # Rodar em 2 nodes para load balancing
      placement:
        constraints:
          - node.role != manager  # Rodar em workers para liberar manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.morea.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.morea.entrypoints=websecure"
        - "traefik.http.routers.morea.tls=true"
        - "traefik.http.routers.morea.tls.certresolver=le"
        - "traefik.http.services.morea.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.morea-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.morea-http.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.morea-http.entrypoints=web"
        - "traefik.http.routers.morea-http.middlewares=morea-https-redirect"

networks:
  fog-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlan_list: 4789
      com.docker.network.driver.overlay.bind_interface: eth0
  morea-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlan_list: 4790
      com.docker.network.driver.overlay.bind_interface: eth0

volumes:
  morea-media:
    driver: local
  morea-static:
    driver: local
  traefik-certs:
    driver: local
